<a href="https://colab.research.google.com/github/faridrizqi46/Time-Series/blob/main/Latihan_LSTM_Predict_Next_Word_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from keras.utils import to_categorical
import numpy as np

In [ ]:
data = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent consequat massa tristique ipsum finibus viverra. Sed placerat velit lobortis tincidunt pretium. Aliquam hendrerit augue id elit sollicitudin euismod quis vel lectus. Ut in lobortis elit, at interdum nunc. Pellentesque sollicitudin est ut mi euismod consequat. Sed eget gravida tortor. Etiam suscipit, tortor ac mattis tempor, elit velit hendrerit velit, scelerisque euismod eros dolor a tortor. Nullam vulputate quam ac metus venenatis, vel faucibus risus blandit. Ut nisi nunc, congue nec elit eu, pulvinar porta felis. Morbi eget nisl mi. Donec mi mauris, dignissim in erat sed, scelerisque iaculis velit. Vestibulum ullamcorper, risus id porta mattis, magna elit consequat lectus, scelerisque scelerisque erat eros non erat. Aliquam auctor enim est, eget bibendum elit aliquam quis. Duis vel vestibulum purus, vitae interdum ligula. Phasellus laoreet risus lectus, ac pharetra velit finibus eget. Nam odio felis, condimentum eget tortor eu, dignissim condimentum felis.

Donec gravida facilisis nulla vitae egestas. Proin gravida vitae ex non volutpat. Pellentesque elementum tempus orci, ac consectetur ipsum vehicula venenatis. Donec leo tortor, vehicula ac metus nec, facilisis tempus nisi. Fusce nec augue sit amet quam auctor sodales. Vivamus scelerisque ipsum nec tempus volutpat. Curabitur vel pellentesque mi. Mauris eu iaculis felis, sed facilisis nulla. Donec ultricies nibh lorem, vulputate mattis sapien euismod vel.

Nam et sodales ipsum. Curabitur vel diam id libero pulvinar posuere non ac velit. In a consequat ante. Integer bibendum quis lectus eget porta. Fusce dui tortor, rhoncus eget ligula non, rhoncus commodo leo. Mauris dictum tellus ut purus pellentesque, quis vestibulum sem finibus. Praesent nec nibh quis arcu rhoncus posuere. Donec feugiat pharetra elementum. Nullam ut fringilla leo, id ultrices lectus. Nam sit amet varius massa, pharetra facilisis tellus. Nullam dictum, sapien at tristique dictum, felis justo efficitur nulla, nec varius erat dui sed sapien. In vitae turpis imperdiet, luctus quam nec, convallis risus. Integer urna diam, luctus non porttitor sed, molestie a nisi. Curabitur viverra hendrerit hendrerit.

Donec finibus vehicula enim, eu interdum ligula condimentum quis. Donec at congue justo. Donec leo odio, ullamcorper eleifend nisl non, molestie scelerisque ante. Etiam facilisis egestas pulvinar. In euismod vestibulum hendrerit. Curabitur rhoncus mi vel neque tincidunt, vel volutpat urna commodo. Sed ante enim, efficitur vel tempus id, pharetra at urna. Nullam sit amet ipsum lacinia, finibus risus sed, pulvinar ante. Proin mi ex, lobortis nec purus id, lacinia feugiat libero. Praesent et odio aliquam, tristique neque consectetur, dictum metus. Donec ut ultricies lacus. Donec faucibus tempor leo ut lobortis. Fusce consectetur accumsan lectus. Fusce nec ligula velit. Maecenas lobortis viverra nulla a rutrum. Curabitur lectus tortor, convallis in nunc interdum, congue euismod justo.

Nulla facilisi. Phasellus laoreet risus nec suscipit consequat. Nam accumsan molestie ipsum, vitae tempus odio sagittis at. Fusce porta nulla sem, id mollis diam hendrerit vehicula. Nam tempor bibendum mauris sed aliquam. In non sapien eget risus imperdiet iaculis. Cras egestas purus in feugiat feugiat. Sed sagittis volutpat sem, a vehicula nisl commodo at. Donec at nibh id est dictum aliquet. Pellentesque at urna vel lacus varius bibendum. Nunc aliquam ipsum vulputate rhoncus rhoncus.
"""

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encode_data = tokenizer.texts_to_sequences([data])[0]
encode_data

[87,
 5,
 88,
 41,
 42,
 43,
 123,
 10,
 63,
 26,
 89,
 64,
 5,
 27,
 65,
 2,
 124,
 11,
 28,
 90,
 125,
 17,
 18,
 91,
 6,
 10,
 92,
 19,
 20,
 3,
 12,
 13,
 7,
 28,
 10,
 8,
 44,
 45,
 29,
 92,
 66,
 13,
 21,
 19,
 26,
 2,
 9,
 67,
 14,
 93,
 94,
 14,
 22,
 68,
 69,
 10,
 11,
 18,
 11,
 23,
 19,
 95,
 88,
 30,
 14,
 46,
 70,
 71,
 22,
 72,
 96,
 3,
 97,
 15,
 126,
 13,
 73,
 45,
 74,
 4,
 10,
 47,
 48,
 49,
 31,
 127,
 9,
 75,
 21,
 1,
 21,
 50,
 98,
 7,
 51,
 2,
 23,
 76,
 11,
 52,
 99,
 15,
 6,
 49,
 68,
 128,
 10,
 26,
 12,
 23,
 23,
 51,
 95,
 16,
 51,
 17,
 100,
 77,
 66,
 9,
 53,
 10,
 17,
 20,
 129,
 3,
 52,
 54,
 32,
 44,
 55,
 101,
 102,
 15,
 12,
 22,
 56,
 11,
 27,
 9,
 33,
 57,
 31,
 78,
 9,
 14,
 47,
 98,
 78,
 31,
 1,
 67,
 34,
 24,
 32,
 79,
 103,
 67,
 32,
 104,
 16,
 58,
 29,
 105,
 35,
 130,
 22,
 43,
 5,
 36,
 96,
 1,
 37,
 14,
 36,
 22,
 72,
 4,
 34,
 35,
 73,
 38,
 4,
 91,
 41,
 42,
 71,
 100,
 106,
 131,
 23,
 5,
 4,
 35,
 58,
 39,
 3,
 29,
 21,
 50,
 47,
 76,
 

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size

144

In [ ]:
sequences = []
for i in range(1,len(encode_data)):
  sequence = encode_data[i-1:i+1]
  sequences.append(sequence)

In [ ]:
sequences

In [ ]:
sequences  =np.array(sequences)

In [ ]:
X,y = sequences[:,0],sequences[:,1]

In [ ]:
X[:5]

array([87,  5, 88, 41, 42])

In [ ]:
y[:5]

array([ 5, 88, 41, 42, 43])

In [ ]:
y = to_categorical(y,num_classes = vocab_size)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size,activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 1, 10)             1440      
_________________________________________________________________
lstm_1 (LSTM)                (None, 50)                12200     
_________________________________________________________________
dense_1 (Dense)              (None, 144)               7344      
Total params: 20,984
Trainable params: 20,984
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=500)

Epoch 1/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4451 - accuracy: 0.1781
Epoch 2/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4462 - accuracy: 0.1742
Epoch 3/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4450 - accuracy: 0.1937
Epoch 4/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4448 - accuracy: 0.2114
Epoch 5/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4457 - accuracy: 0.1918
Epoch 6/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4456 - accuracy: 0.1820
Epoch 7/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4444 - accuracy: 0.1820
Epoch 8/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4454 - accuracy: 0.1840
Epoch 9/500
16/16 [==============================] - 0s 3ms/step - loss: 1.4436 - accuracy: 0.1879
Epoch 10/500
16/16 [==============================] - 0s 2ms/step - loss: 1.4451 - accuracy: 0.1800
Epoch 11/

In [ ]:
def generate_seq(model,tokenizer,enter_text,n_pred):
  in_text, result = enter_text,enter_text
  for _ in range(n_pred):
    encoded = tokenizer.texts_to_sequences([in_text])[0]
    encoded = np.array(encoded)

    yhat = model.predict_classes(encoded)

    out_word  =''
    for word,index in tokenizer.word_index.items():
      if index == yhat:
        out_word = word
        break
    in_text, result = out_word, result + ' ' + out_word
  return result

In [ ]:
print(generate_seq(model,tokenizer,'urna',10))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


urna commodo sed molestie a rutrum curabitur vel tempus orci ac
